name: login_tester
description: login tester

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <=3.0.1"

dependencies:
  flutter:
    sdk: flutter
  backendless_sdk: 7.3.5
  go_router: ^6.5.5
  provider: 6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  yaml: ^3.1.1
  logger: ^1.3.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  # flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true